export const categories = [
  { name: 'Gadgets', id: 0 },
  { name: 'Accesories', id: 1 },
  { name: 'Hobbies', id: 2 },
  { name: 'Home Decor', id: 3 },
  { name: 'Household Supplies', id: 4 },
  { name: 'Fashion', id: 5 },
  { name: 'Shoes', id: 6 },
  { name: 'Baby & Kids', id: 7 },
  { name: 'Wallet & Bags', id: 8 },
  { name: 'Phone Upgrades', id: 9 },
  { name: 'Tools', id: 10 },
  { name: 'Tops', id: 11 },
  { name: 'Pet Accesories', id: 12 },
  { name: 'Stationary', id: 13 },
  { name: 'Underwear', id: 14 },
  { name: 'Kitchen', id: 15 },
  { name: 'Bottoms', id: 16 },
  { name: 'Stationary', id: 17 }
]
